addons:
  ssh_known_hosts: dev.dead-drop.me
  
before_deploy:
- openssl aes-256-cbc -k $encrypted_bacf8c57c100_key -iv $encrypted_bacf8c57c100_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/<dir> bkeenan@dev.dead-drop.me:path/to/files
  on:
    branch: master
